libxc_la_FUNC_SOURCES = \
	bessel.c \
	expint_e1.c \
	faddeeva.c \
	func_info.c \
	func_reference.c \
	functionals.c \
	gga.c \
	gga_c_acgga.c \
	gga_c_acggap.c \
	gga_c_am05.c \
	gga_c_bmk.c \
	gga_c_ccdf.c \
	gga_c_chachiyo.c \
	gga_c_cs1.c \
	gga_c_ft97.c \
	gga_c_gapc.c \
	gga_c_gaploc.c \
	gga_c_hcth_a.c \
	gga_c_lm.c \
	gga_c_lyp.c \
	gga_c_lypr.c \
	gga_c_op_b88.c \
	gga_c_op_g96.c \
	gga_c_op_pbe.c \
	gga_c_op_pw91.c \
	gga_c_op_xalpha.c \
	gga_c_optc.c \
	gga_c_p86.c \
	gga_c_p86vwn.c \
	gga_c_pbe.c \
	gga_c_pbe_erf_gws.c \
	gga_c_pbe_vwn.c \
	gga_c_pbeloc.c \
	gga_c_pw91.c \
	gga_c_q2d.c \
	gga_c_regtpss.c \
	gga_c_revtca.c \
	gga_c_scan_e0.c \
	gga_c_sg4.c \
	gga_c_sogga11.c \
	gga_c_tca.c \
	gga_c_w94.c \
	gga_c_wi.c \
	gga_c_wl.c \
	gga_c_zpbeint.c \
	gga_c_zvpbeint.c \
	gga_c_zvpbeloc.c \
	gga_k_apbe.c \
	gga_k_apbeint.c \
	gga_k_dk.c \
	gga_k_exp4.c \
	gga_k_gds08.c \
	gga_k_lc94.c \
	gga_k_lgap.c \
	gga_k_lgap_ge.c \
	gga_k_lkt.c \
	gga_k_llp.c \
	gga_k_meyer.c \
	gga_k_mpbe.c \
	gga_k_ol1.c \
	gga_k_ol2.c \
	gga_k_pearson.c \
	gga_k_pg.c \
	gga_k_pw86.c \
	gga_k_rational_p.c \
	gga_k_tflw.c \
	gga_k_thakkar.c \
	gga_k_vt84f.c \
	gga_x_2d_b86.c \
	gga_x_2d_b86_mgc.c \
	gga_x_2d_b88.c \
	gga_x_2d_pbe.c \
	gga_x_airy.c \
	gga_x_ak13.c \
	gga_x_am05.c \
	gga_x_b86.c \
	gga_x_b88.c \
	gga_x_bayesian.c \
	gga_x_beefvdw.c \
	gga_x_bkl.c \
	gga_x_bpccac.c \
	gga_x_c09x.c \
	gga_x_cap.c \
	gga_x_chachiyo.c \
	gga_x_dk87.c \
	gga_x_ev93.c \
	gga_x_fd_lb94.c \
	gga_x_ft97.c \
	gga_x_g96.c \
	gga_x_gg99.c \
	gga_x_hcth_a.c \
	gga_x_hjs.c \
	gga_x_hjs_b88_v2.c \
	gga_x_htbs.c \
	gga_x_ityh.c \
	gga_x_ityh_optx.c \
	gga_x_ityh_pbe.c \
	gga_x_kt.c \
	gga_x_lb.c \
	gga_x_lg93.c \
	gga_x_lspbe.c \
	gga_x_lsrpbe.c \
	gga_x_lv_rpw86.c \
	gga_x_mpbe.c \
	gga_x_n12.c \
	gga_x_ncap.c \
	gga_x_ol2.c \
	gga_x_optx.c \
	gga_x_pbe.c \
	gga_x_pbe_erf_gws.c \
	gga_x_pbea.c \
	gga_x_pbeint.c \
	gga_x_pbepow.c \
	gga_x_pbetrans.c \
	gga_x_pw86.c \
	gga_x_pw91.c \
	gga_x_q1d.c \
	gga_x_q2d.c \
	gga_x_rge2.c \
	gga_x_rpbe.c \
	gga_x_s12.c \
	gga_x_sfat.c \
	gga_x_sfat_pbe.c \
	gga_x_sg4.c \
	gga_x_sogga11.c \
	gga_x_ssb_sw.c \
	gga_x_vmt.c \
	gga_x_vmt84.c \
	gga_x_wc.c \
	gga_x_wpbeh.c \
	gga_xc_1w.c \
	gga_xc_b97.c \
	gga_xc_edf1.c \
	gga_xc_oblyp_d.c \
	gga_xc_th1.c \
	gga_xc_th2.c \
	gga_xc_th3.c \
	gga_xc_vv10.c \
	hyb_gga_x_cam_s12.c \
	hyb_gga_xc_b1wc.c \
	hyb_gga_xc_b3lyp.c \
	hyb_gga_xc_cam_b3lyp.c \
	hyb_gga_xc_cam_o3lyp.c \
	hyb_gga_xc_camy_b3lyp.c \
	hyb_gga_xc_camy_blyp.c \
	hyb_gga_xc_case21.c \
	hyb_gga_xc_edf2.c \
	hyb_gga_xc_hse.c \
	hyb_gga_xc_lc_blyp.c \
	hyb_gga_xc_lcy_blyp.c \
	hyb_gga_xc_lcy_pbe.c \
	hyb_gga_xc_o3lyp.c \
	hyb_gga_xc_pbeh.c \
	hyb_gga_xc_wb97.c \
	hyb_lda_xc_bn05.c \
	hyb_lda_xc_cam_lda0.c \
	hyb_mgga_x_dldf.c \
	hyb_mgga_x_js18.c \
	hyb_mgga_x_m05.c \
	hyb_mgga_x_mvsh.c \
	hyb_mgga_x_pjs18.c \
	hyb_mgga_x_wr2scan.c \
	hyb_mgga_xc_b88b95.c \
	hyb_mgga_xc_br3p86.c \
	hyb_mgga_xc_coach.c \
	hyb_mgga_xc_gas22.c \
	hyb_mgga_xc_kcis.c \
	hyb_mgga_xc_r2scan.c \
	hyb_mgga_xc_tpssh.c \
	hyb_mgga_xc_wb97mv.c \
	hybrids.c \
	integrate.c \
	lda.c \
	lda_c_1d_css.c \
	lda_c_1d_loos.c \
	lda_c_2d_amgb.c \
	lda_c_2d_prm.c \
	lda_c_chachiyo.c \
	lda_c_chachiyo_mod.c \
	lda_c_epc17.c \
	lda_c_epc18.c \
	lda_c_gk72.c \
	lda_c_gombas.c \
	lda_c_hl.c \
	lda_c_lp96.c \
	lda_c_ml1.c \
	lda_c_pk09.c \
	lda_c_pmgb06.c \
	lda_c_pw.c \
	lda_c_pw_erf.c \
	lda_c_pz.c \
	lda_c_rc04.c \
	lda_c_rpa.c \
	lda_c_rpaf.c \
	lda_c_vwn.c \
	lda_c_vwn_1.c \
	lda_c_vwn_2.c \
	lda_c_vwn_3.c \
	lda_c_vwn_4.c \
	lda_c_vwn_rpa.c \
	lda_c_w20.c \
	lda_c_wigner.c \
	lda_k_tf.c \
	lda_k_zlp.c \
	lda_x.c \
	lda_x_1d_exponential.c \
	lda_x_1d_soft.c \
	lda_x_2d.c \
	lda_x_erf.c \
	lda_x_rel.c \
	lda_x_sloc.c \
	lda_x_yukawa.c \
	lda_xc_1d_ehwlrg.c \
	lda_xc_ksdt.c \
	lda_xc_teter93.c \
	lda_xc_th_fl.c \
	lda_xc_tih.c \
	lda_xc_zlp.c \
	math_brent.c \
	mgga.c \
	mgga_c_b88.c \
	mgga_c_b94.c \
	mgga_c_bc95.c \
	mgga_c_cc.c \
	mgga_c_ccalda.c \
	mgga_c_cs.c \
	mgga_c_kcis.c \
	mgga_c_kcisk.c \
	mgga_c_lak.c \
	mgga_c_ltapw.c \
	mgga_c_m05.c \
	mgga_c_m06l.c \
	mgga_c_m08.c \
	mgga_c_mscan.c \
	mgga_c_pkzb.c \
	mgga_c_r2scan.c \
	mgga_c_r2scanl.c \
	mgga_c_revscan.c \
	mgga_c_revtpss.c \
	mgga_c_rmggac.c \
	mgga_c_rppscan.c \
	mgga_c_rregtm.c \
	mgga_c_rscan.c \
	mgga_c_scan.c \
	mgga_c_scanl.c \
	mgga_c_tpss.c \
	mgga_c_tpssloc.c \
	mgga_c_vsxc.c \
	mgga_k_csk.c \
	mgga_k_csk_loc.c \
	mgga_k_gea2.c \
	mgga_k_gea4.c \
	mgga_k_lk.c \
	mgga_k_pc07.c \
	mgga_k_pgslb.c \
	mgga_k_rda.c \
	mgga_x_2d_js17.c \
	mgga_x_2d_prhg07.c \
	mgga_x_2d_prp10.c \
	mgga_x_br89.c \
	mgga_x_br89_explicit.c \
	mgga_x_edmgga.c \
	mgga_x_eel.c \
	mgga_x_ft98.c \
	mgga_x_gdme.c \
	mgga_x_gvt4.c \
	mgga_x_gx.c \
	mgga_x_jk.c \
	mgga_x_ktbm.c \
	mgga_x_lak.c \
	mgga_x_lta.c \
	mgga_x_m06l.c \
	mgga_x_m08.c \
	mgga_x_m11.c \
	mgga_x_m11_l.c \
	mgga_x_mbeef.c \
	mgga_x_mbeefvdw.c \
	mgga_x_mbr.c \
	mgga_x_mbrxc_bg.c \
	mgga_x_mbrxh_bg.c \
	mgga_x_mcml.c \
	mgga_x_mggac.c \
	mgga_x_mn12.c \
	mgga_x_ms.c \
	mgga_x_msb.c \
	mgga_x_msb86bl.c \
	mgga_x_mscan.c \
	mgga_x_mspbel.c \
	mgga_x_msrpbel.c \
	mgga_x_mvs.c \
	mgga_x_pbe_gx.c \
	mgga_x_pkzb.c \
	mgga_x_r2scan.c \
	mgga_x_r2scanl.c \
	mgga_x_r4scan.c \
	mgga_x_regtm.c \
	mgga_x_regtpss.c \
	mgga_x_revtm.c \
	mgga_x_rlda.c \
	mgga_x_rppscan.c \
	mgga_x_rscan.c \
	mgga_x_rtpss.c \
	mgga_x_sa_tpss.c \
	mgga_x_scan.c \
	mgga_x_scanl.c \
	mgga_x_sregtm_v1.c \
	mgga_x_sregtm_v2.c \
	mgga_x_sregtm_v3.c \
	mgga_x_task.c \
	mgga_x_tau_hcth.c \
	mgga_x_tb09.c \
	mgga_x_th.c \
	mgga_x_tm.c \
	mgga_x_tpss.c \
	mgga_x_vcml.c \
	mgga_x_vt84.c \
	mgga_xc_b97mv.c \
	mgga_xc_b98.c \
	mgga_xc_cc06.c \
	mgga_xc_hle17.c \
	mgga_xc_lp90.c \
	mgga_xc_otpss_d.c \
	mgga_xc_zlp.c \
	mix_func.c \
	references.c \
	special_functions.c \
	util.c \
	version.c
